name: Image build

on:
  push

  # Run tests for any PRs.
  # pull_request:

jobs:
  push_verify_release:
    # Ensure test job passes before pushing image.
    # needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.3"
      - uses: imjasonh/setup-ko@v0.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build push verify-conformance-release image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: verify-conformance-release
        run: |
          set -x
          IMAGE_ID=$(echo $ECR_REGISTRY/$ECR_REPOSITORY | tr '[A-Z]' '[a-z]')
          export KO_DOCKER_REPO="${IMAGE_ID}"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if [ -n "${VERSION:-}" ] && [ ! "${VERSION:-}" = "${{ github.event.repository.default_branch }}" ]; then
            BRANCH="-${VERSION:-}"
          fi
          ko build \
            --bare \
            --push \
            --platform linux/amd64,linux/arm64,linux/arm64/v8 \
            --tags "latest${BRANCH:-},${{ steps.slug.outputs.sha8 }}" \
            .
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
