name: code quality check

on:
  push:
    branches:
      - '!main'
  pull_request: {}
  workflow_dispatch: {}

jobs:
  gobuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: gobuild
        id: gobuild
        run: ./hack/verify-gobuild.sh
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: gofmt
        id: gofmt
        run: ./hack/verify-gofmt.sh
  goimports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: goimports
        id: goimports
        run: ./hack/verify-goimports.sh
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache: false
      - name: write .golangci.yml
        if: ${{ inputs.config }}
        run: |
          echo "Using config:"
          echo '${{ inputs.config }}' | tee .golangci.yml
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: v1.55.2
          args: --timeout 10m
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: golint
        id: golint
        run: ./hack/verify-golint.sh
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: gotest
        id: gotest
        run: ./hack/verify-gotest.sh
  govet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: govet
        id: govet
        run: ./hack/verify-govet.sh
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: govulncheck
        id: govulncheck
        run: ./hack/verify-govulncheck.sh
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: spellcheck
        id: spellcheck
        run: ./hack/verify-spellcheck.sh
